'use client'

import { useState } from 'react'
import { Activity, AlertTriangle, ArrowRight, Bell, CalendarDays, ChevronDown, CircleHelp, Clock3, FileText, HeartPulse, Home, Languages, Leaf, Menu, MessageCircle, Mic, Paperclip, PhoneCall, Search, Send, ShieldCheck, Sparkles, Stethoscope, UserRound, X } from 'lucide-react'

const navItems = [
  { label: 'Home', icon: Home }, { label: 'AI Assistant', icon: MessageCircle }, { label: 'Health History', icon: FileText },
  { label: 'Image Analysis', icon: Activity }, { label: 'Nearby Care', icon: Search }, { label: 'Health Education', icon: CircleHelp }, { label: 'Reminders', icon: Bell },
]
const history = [
  { title: 'Mild headache & fatigue', date: 'Today, 10:42 AM', risk: 'Low', color: 'emerald' }, { title: 'Seasonal cough', date: '18 Aug 2026, 6:15 PM', risk: 'Moderate', color: 'amber' }, { title: 'Stomach discomfort', date: '12 Aug 2026, 9:20 AM', risk: 'Low', color: 'emerald' },
]
const quickActions = [
  { title: 'Check symptoms', copy: 'Understand what your body may be telling you', icon: Stethoscope, tone: 'blue' }, { title: 'Upload an image', copy: 'Get preliminary visual health guidance', icon: Activity, tone: 'violet' }, { title: 'Find nearby care', copy: 'Hospitals, clinics and pharmacies near you', icon: Search, tone: 'teal' }, { title: 'Emergency info', copy: 'Know what to do when every second matters', icon: AlertTriangle, tone: 'red' },
]

export default function App() {
  const [active, setActive] = useState('Home')
  const [language, setLanguage] = useState('EN')
  const [mobileNav, setMobileNav] = useState(false)
  const [emergencyOpen, setEmergencyOpen] = useState(false)
  const [message, setMessage] = useState('')
  const [chatStarted, setChatStarted] = useState(false)
  const sendMessage = () => { if (!message.trim()) return; setChatStarted(true); setMessage('') }

  return (
    <main className="min-h-screen bg-[#F8FAFC] text-[#0F172A]"><div className="flex min-h-screen">
      <aside className={`${mobileNav ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-40 w-[278px] border-r border-slate-200 bg-white px-5 py-6 transition-transform lg:static lg:translate-x-0`}>
        <div className="flex items-center justify-between px-2"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#1B6CA8] text-white shadow-lg shadow-blue-900/15"><HeartPulse size={24} /></div><div><div className="text-lg font-bold tracking-tight">Aarogya<span className="text-[#1B6CA8]">GPT</span></div><div className="text-[11px] font-medium text-slate-400">Your health companion</div></div></div><button onClick={() => setMobileNav(false)} className="rounded-lg p-2 text-slate-400 lg:hidden"><X size={20} /></button></div>
        <div className="mt-10 space-y-1"><p className="px-3 pb-3 text-[10px] font-bold uppercase tracking-[0.18em] text-slate-400">Workspace</p>{navItems.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMobileNav(false) }} className={`flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-sm font-semibold transition ${active === label ? 'bg-blue-50 text-[#1B6CA8]' : 'text-slate-500 hover:bg-slate-50 hover:text-slate-900'}`}><Icon size={19} />{label}{label === 'Reminders' && <span className="ml-auto rounded-full bg-amber-100 px-2 py-0.5 text-[10px] text-amber-700">3</span>}</button>)}</div>
        <div className="mt-8 border-t border-slate-100 pt-6"><button onClick={() => setActive('Profile')} className="flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-sm font-semibold text-slate-500 hover:bg-slate-50"><UserRound size={19} />Profile</button><button onClick={() => setEmergencyOpen(true)} className="mt-3 flex min-h-12 w-full items-center gap-3 rounded-xl bg-red-50 px-3 text-sm font-bold text-red-600 transition hover:bg-red-100"><AlertTriangle size={19} />Emergency help <ArrowRight className="ml-auto" size={16} /></button></div>
        <div className="absolute bottom-6 left-6 right-6 rounded-2xl bg-[#F0F7FC] p-4"><div className="flex items-start gap-2"><ShieldCheck size={17} className="mt-0.5 text-[#1B6CA8]" /><p className="text-[11px] leading-5 text-slate-500">Your conversations are private and secure.</p></div></div>
      </aside>
      <section className="min-w-0 flex-1"><header className="flex h-[76px] items-center justify-between border-b border-slate-200 bg-white/85 px-5 backdrop-blur md:px-10"><div className="flex items-center gap-3"><button onClick={() => setMobileNav(true)} className="rounded-xl p-2 text-slate-500 lg:hidden"><Menu size={22} /></button><div className="hidden text-sm font-semibold text-slate-400 md:block">{active === 'Home' ? 'Overview' : active}</div></div><div className="flex items-center gap-3"><button onClick={() => setLanguage(language === 'EN' ? 'HI' : 'EN')} className="flex h-10 items-center gap-2 rounded-xl border border-slate-200 px-3 text-xs font-bold text-slate-600 hover:bg-slate-50"><Languages size={16} className="text-[#1B6CA8]" />{language}<ChevronDown size={14} /></button><button className="relative flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 text-slate-500"><Bell size={18} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-red-500" /></button><div className="hidden h-9 w-px bg-slate-200 sm:block" /><div className="flex items-center gap-2"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#DCEEF9] text-sm font-bold text-[#1B6CA8]">RK</div><div className="hidden sm:block"><p className="text-xs font-bold">Rahul Kumar</p><p className="text-[11px] text-slate-400">Member since 2026</p></div></div></div></header>
        <div className="mx-auto max-w-[1400px] px-5 py-7 md:px-10 md:py-10"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-sm font-medium text-[#1B6CA8]">Tuesday, 20 August 2026</p><h1 className="text-3xl font-bold tracking-tight md:text-[38px]">Namaste, Rahul <span className="inline-block">👋</span></h1><p className="mt-2 text-base text-slate-500">How can we help you feel your best today?</p></div><div className="flex items-center gap-2 rounded-full border border-emerald-100 bg-emerald-50 px-4 py-2 text-xs font-semibold text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-500" />All systems healthy</div></div>
          <div className="grid gap-6 xl:grid-cols-[1fr_350px]"><div className="space-y-6"><div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#134E7F] via-[#1B6CA8] to-[#2787be] p-7 text-white shadow-xl shadow-blue-900/10 md:p-9"><div className="relative z-10 max-w-[580px]"><div className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-blue-100"><Sparkles size={15} />Personalised for you</div><h2 className="max-w-lg text-2xl font-bold leading-tight md:text-3xl">A little clarity can make a big difference.</h2><p className="mt-3 max-w-lg text-sm leading-6 text-blue-100">Share what you are feeling in English or Hindi. Get simple, thoughtful guidance on what to do next.</p><button onClick={() => setActive('AI Assistant')} className="mt-7 flex min-h-11 items-center gap-2 rounded-xl bg-white px-5 text-sm font-bold text-[#134E7F] shadow-lg hover:bg-blue-50">Start a health check <ArrowRight size={17} /></button></div><div className="absolute -right-12 -top-16 h-64 w-64 rounded-full border-[28px] border-white/10" /><div className="absolute -bottom-24 right-20 h-52 w-52 rounded-full border-[18px] border-white/10" /><Leaf className="absolute bottom-8 right-12 hidden text-white/20 md:block" size={90} /></div>
            <div><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-bold">How can we help?</h2><p className="mt-1 text-sm text-slate-500">Take the next step towards better health</p></div><button className="hidden text-sm font-bold text-[#1B6CA8] sm:block">View all <ArrowRight className="ml-1 inline" size={14} /></button></div><div className="grid gap-3 sm:grid-cols-2">{quickActions.map(({ title, copy, icon: Icon, tone }) => <button key={title} onClick={() => tone === 'red' ? setEmergencyOpen(true) : setActive(title === 'Check symptoms' ? 'AI Assistant' : title)} className="group flex min-h-[128px] items-start gap-4 rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-md"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${tone === 'blue' ? 'bg-blue-50 text-blue-600' : tone === 'violet' ? 'bg-violet-50 text-violet-600' : tone === 'teal' ? 'bg-teal-50 text-teal-600' : 'bg-red-50 text-red-600'}`}><Icon size={21} /></div><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{copy}</p><span className="mt-3 inline-flex items-center text-xs font-bold text-[#1B6CA8] opacity-0 transition group-hover:opacity-100">Explore <ArrowRight className="ml-1" size={13} /></span></div></button>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-amber-50 text-amber-600"><Sparkles size={21} /></div><div><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-amber-600">Health tip of the day</p><h3 className="mt-1 text-sm font-bold">Small habits, lasting health</h3><p className="mt-1 text-sm leading-6 text-slate-500">Staying hydrated can support energy, digestion and concentration throughout your day.</p></div></div></div></div>
            <div className="space-y-6"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">Recent health checks</h2><p className="mt-1 text-xs text-slate-400">Your latest conversations</p></div><ArrowRight size={17} className="text-slate-400" /></div><div className="space-y-4">{history.map(item => <div key={item.title} className="flex items-center gap-3"><div className={`h-2.5 w-2.5 rounded-full ${item.color === 'emerald' ? 'bg-emerald-500' : 'bg-amber-500'}`} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.title}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-slate-400"><Clock3 size={12} />{item.date}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${item.color === 'emerald' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{item.risk}</span></div>)}</div><button onClick={() => setActive('Health History')} className="mt-5 w-full rounded-xl border border-slate-200 py-2.5 text-xs font-bold text-[#1B6CA8] hover:bg-blue-50">View health history</button></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Upcoming reminders</h2><p className="mt-1 text-xs text-slate-400">Stay on top of your wellbeing</p></div><CalendarDays size={19} className="text-slate-400" /></div><div className="space-y-3"><div className="flex items-center gap-3 rounded-xl bg-blue-50/70 p-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-[#1B6CA8]"><Bell size={16} /></div><div className="flex-1"><p className="text-xs font-bold">Evening walk</p><p className="mt-1 text-[11px] text-slate-500">Today · 6:30 PM</p></div><span className="h-2 w-2 rounded-full bg-emerald-500" /></div><div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-violet-600"><CalendarDays size={16} /></div><div className="flex-1"><p className="text-xs font-bold">Doctor appointment</p><p className="mt-1 text-[11px] text-slate-500">Tomorrow · 11:00 AM</p></div><span className="h-2 w-2 rounded-full bg-emerald-500" /></div></div><button onClick={() => setActive('Reminders')} className="mt-4 text-xs font-bold text-[#1B6CA8]">Manage reminders <ArrowRight className="ml-1 inline" size={13} /></button></div><div className="rounded-2xl border border-blue-100 bg-[#F0F7FC] p-5"><div className="flex gap-3"><ShieldCheck size={19} className="shrink-0 text-[#1B6CA8]" /><p className="text-xs leading-5 text-slate-500"><strong className="text-slate-700">A note from AarogyaGPT:</strong> This app offers general health guidance, not a diagnosis. Please consult a qualified healthcare professional for medical advice.</p></div></div></div></div>
        </div>
      </section>
    </div>
    {active === 'AI Assistant' && <div className="fixed bottom-5 right-5 z-30 w-[min(390px,calc(100vw-2rem))] overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl"><div className="flex items-center justify-between bg-[#134E7F] p-4 text-white"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/15"><HeartPulse size={18} /></div><div><p className="text-sm font-bold">AI Health Assistant</p><p className="text-[10px] text-blue-100">Here to help you understand</p></div></div><button onClick={() => setActive('Home')} className="rounded-lg p-1 hover:bg-white/10"><X size={18} /></button></div><div className="h-52 space-y-3 overflow-y-auto bg-slate-50 p-4 text-xs"><div className="max-w-[85%] rounded-2xl rounded-tl-sm border border-slate-200 bg-white p-3 leading-5 text-slate-600 shadow-sm">Hi Rahul, I&apos;m here to help. Tell me what you&apos;re experiencing, and please share when it started.</div>{chatStarted && <><div className="ml-auto max-w-[85%] rounded-2xl rounded-tr-sm bg-[#1B6CA8] p-3 leading-5 text-white">Thanks for sharing. Let&apos;s understand this together.</div><div className="max-w-[85%] rounded-2xl rounded-tl-sm border border-slate-200 bg-white p-3 leading-5 text-slate-600 shadow-sm">For personalised guidance, a healthcare professional should review your symptoms.</div></>}</div><div className="border-t border-slate-100 bg-white p-3"><div className="flex items-center gap-2 rounded-xl border border-slate-200 px-3"><button className="text-slate-400"><Paperclip size={17} /></button><input value={message} onChange={e => setMessage(e.target.value)} onKeyDown={e => e.key === 'Enter' && sendMessage()} placeholder="Describe your symptoms..." className="h-11 min-w-0 flex-1 bg-transparent text-xs outline-none placeholder:text-slate-400" /><button className="text-slate-400"><Mic size={17} /></button><button onClick={sendMessage} className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#1B6CA8] text-white"><Send size={14} /></button></div><p className="mt-2 text-center text-[10px] text-slate-400">AI-generated. For general guidance only. Not a medical diagnosis.</p></div></div>}
    {emergencyOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl md:p-8"><div className="flex justify-end"><button onClick={() => setEmergencyOpen(false)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={20} /></button></div><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-red-100 text-red-600"><AlertTriangle size={28} /></div><h2 className="mt-5 text-center text-2xl font-bold text-slate-900">This may be a medical emergency</h2><p className="mt-2 text-center text-sm leading-6 text-slate-500">If you are in immediate danger, do not use this app. Get urgent help now.</p><div className="mt-6 space-y-3"><a href="tel:112" className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-red-600 text-sm font-bold text-white hover:bg-red-700"><PhoneCall size={18} />Call Emergency Services · 112</a><button onClick={() => { setEmergencyOpen(false); setActive('Nearby Care') }} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border border-slate-200 text-sm font-bold text-slate-700 hover:bg-slate-50"><Search size={18} />Find Emergency Hospital</button></div><div className="mt-6 rounded-xl bg-red-50 p-4 text-xs leading-5 text-red-800"><strong>Seek immediate help for:</strong> severe breathing difficulty, loss of consciousness, severe chest pain, stroke signs, severe allergic reaction, uncontrolled bleeding, or suspected poisoning.</div></div></div>}
    </main>
  )
}